SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 640
SCREEN_CAPTION = "Banana catcher"

BASKET_POSITION_HEIGHT = SCREEN_HEIGHT - (1/32)*SCREEN_HEIGHT
BASKET_IMAGE_PATH = "images/basket.png"
BASKET_SCALE = 0.1

BANANA_IMAGE_PATH = "images/banana.png"
BANANA_SCALE = 0.1
BANANA_SPEED = 5


